config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :transactions do
    resources :comments
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :transactions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :owner, foreign_key: "transaction_id", class_name: "Transaction"
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  has_many :comments
  belongs_to :category
  validates :category_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new' 
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def index
    @transaction = Transaction.find(params[:transaction_id])
    redirect_to transaction_path(@transaction)
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @transaction = Transaction.find(params[:transaction_id])
    @comment = Comment.new(comment_params)
    @comment.owner = @transaction
    if @comment.save
      redirect_to  transaction_path(@transaction)
    else
      render 'new'
    end
  end

  def destroy
    @transaction = Transaction.find(params[:transaction_id])
    @comment = @transaction.comments.find(params[:id])
    @comment.destroy
    redirect_to transaction_path(@transaction)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
    @comment = @transaction.comments.build
  end

  def new
    @transaction = Transaction.new
    
  end

  def create
    @transaction = Transaction.create(transaction_params)

    if @transaction.save
      redirect_to @transaction
    else
      render 'new'
    end
  end

end

private
  def transaction_params
    params.require(:transaction).permit(:amount, :category_id)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <td> <%= category.name %> </td>
    <td> <% category.transactions.each do |transaction| %> 
    <%= transaction.amount %>
    <% end %>
    </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h3>Add a category</h3>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name</strong>
  <%= @category.name %>
  <% @category.transactions.each do |transaction| %> 
    <%= transaction.amount %>
  <% end %>
</p>

<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<%= @comment.body %>

app/views/comments/_form.html.erb
<%= form_for([@transaction, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction:</strong>
  <%= @comment.transaction %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
  <%= form_for @transaction do |f| %>
    <p>
      <%= f.label :amount %><br>
      <%= f.text_field :amount %>
    </p>
    <p>
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {:prompt => :true} %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Category</th>
      <th>Comments</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
      <td><%= link_to (number_to_currency transaction.amount), transaction_path(transaction) %></td>
        <td><%= link_to (transaction.category.name), category_path(transaction.category) %></td>
      <td><%= transaction.comments.length %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h3>Add a transaction</h3>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <p><%= @transaction.amount %></p>
  <p><%= @transaction.category.name %></p>
  <h2>Comments</h2>
  <% @transaction.comments.each do |comment| %>
    <p>
      <%= comment.body %>
      <%= link_to 'Delete', [@transaction, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>